---
# Step 1. Authenticate and retrieve access token
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars_files: vars.yml
  vars_prompt:
    - name: venafi_user
      prompt: "Venafi username"
      private: false
      default: <ACCOUNT>
    - name: venafi_pwd
      prompt: "Venafi password"
      private: true
    - name: cert_pwd
      prompt: "Certificate password"
      private: true

  tasks:
    - include_tasks: auth.yml
    - include_tasks: format_san_list.yml
    - include_tasks: request_certs.yml
    - include_tasks: retrieve_certs.yml
    - include_tasks: revoke_auth.yml
